language: csharp
solution: EconTools.sln
mono:
  - 4.4.2
install:
  - nuget restore EconTools.sln
  - nuget install NUnit.Console -Version 3.7.0 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release EconTools.sln
  - mono ./testrunner/NUnit.ConsoleRunner.3.7.0/tools/nunit3-console.exe ./DividendFlowCalculatorTest/bin/Release/DividendsCalcTest.dll
