language: csharp
solution: EconTools.sln
mono:
  - latest
install:
  - nuget restore EconTools.sln
  - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release EconTools.sln
  - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe ./DividendFlowCalculatorTest/bin/Release/DividendsCalcTest.dll
