
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.Fixed fixed1;
	
	private global::Gtk.Entry entryInput;
	
	private global::Gtk.Button buttonOpen;
	
	private global::Gtk.Button buttonCalc;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.fixed1 = new global::Gtk.Fixed ();
		this.fixed1.Name = "fixed1";
		this.fixed1.HasWindow = false;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.entryInput = new global::Gtk.Entry ();
		this.entryInput.WidthRequest = 220;
		this.entryInput.CanFocus = true;
		this.entryInput.Name = "entryInput";
		this.entryInput.IsEditable = true;
		this.entryInput.InvisibleChar = '●';
		this.fixed1.Add (this.entryInput);
		global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.entryInput]));
		w1.X = 10;
		w1.Y = 13;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.buttonOpen = new global::Gtk.Button ();
		this.buttonOpen.CanFocus = true;
		this.buttonOpen.Name = "buttonOpen";
		this.buttonOpen.UseUnderline = true;
		this.buttonOpen.Label = global::Mono.Unix.Catalog.GetString ("Open");
		this.fixed1.Add (this.buttonOpen);
		global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.buttonOpen]));
		w2.X = 242;
		w2.Y = 13;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.buttonCalc = new global::Gtk.Button ();
		this.buttonCalc.CanFocus = true;
		this.buttonCalc.Name = "buttonCalc";
		this.buttonCalc.UseUnderline = true;
		this.buttonCalc.Label = global::Mono.Unix.Catalog.GetString ("Calc");
		this.fixed1.Add (this.buttonCalc);
		global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.buttonCalc]));
		w3.X = 303;
		w3.Y = 13;
		this.Add (this.fixed1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 355;
		this.DefaultHeight = 55;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.buttonOpen.Clicked += new global::System.EventHandler (this.buttonOpenClicked);
		this.buttonCalc.Clicked += new global::System.EventHandler (this.buttonCalcClicked);
	}
}
